insert into employees (id, firstname, lastname, age, gender, phone, position) values (1, 'Vaughn', 'Nacci', 38, 'Male', '989-137-0795', 'Engineer IV');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (2, 'Daile', 'Treadaway', 29, 'Female', '434-596-0586', 'Developer III');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (3, 'Helaina', 'Flattman', 59, 'Female', '361-404-6137', 'General Manager');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (4, 'Colas', 'Kenny', 58, 'Male', '561-745-9974', 'VP Product Management');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (5, 'Gordan', 'Legister', 54, 'Male', '587-546-7041', 'Marketing Manager');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (6, 'Locke', 'Agnolo', 27, 'Male', '915-600-9161', 'Community Outreach Specialist');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (7, 'Sanson', 'Ellis', 31, 'Male', '282-670-2397', 'General Manager');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (8, 'Hodge', 'Shann', 31, 'Male', '564-117-1375', 'Project Manager');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (9, 'Sharla', 'Sloam', 38, 'Female', '162-415-8454', 'VP Sales');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (10, 'Rycca', 'Mellodey', 53, 'Female', '628-527-6912', 'Librarian');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (11, 'Koren', 'Layburn', 47, 'Female', '618-971-6803', 'VP Quality Control');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (12, 'Fletcher', 'Bellay', 34, 'Male', '821-161-9850', 'Chief Design Engineer');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (13, 'North', 'Petyankin', 42, 'Male', '731-755-5154', 'Accountant III');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (14, 'Jacklin', 'Sellers', 24, 'Female', '237-800-0345', 'Analyst Programmer');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (15, 'Babette', 'Healy', 22, 'Female', '503-407-9169', 'Compensation Analyst');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (16, 'Anet', 'Mushart', 30, 'Female', '448-174-7151', 'Staff Scientist');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (17, 'Randall', 'Kienl', 28, 'Male', '366-542-2510', 'Graphic Designer');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (18, 'Nealon', 'Gather', 53, 'Male', '610-752-9664', 'Analog Circuit Design manager');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (19, 'Paulie', 'O''Brian', 47, 'Female', '192-342-4984', 'Software Engineer IV');
insert into employees (id, firstname, lastname, age, gender, phone, position) values (20, 'Galvin', 'Whellans', 24, 'Male', '469-860-8206', 'Media Manager I');
